version: '3.4'

services:
  nodejs_mongo_docker:
    container_name: nodejs_mongo_docker
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
    volumes:
      - data:/data/db
volumes:
  data: